name: regularized-mar-vs-lstm-in-forecasting-implied-volatility-surfaces
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - pytorch
  - lightning